#!/bin/bash

# Exit on error
set -e
# Print every command before running
set -x

# Read inputs
GITHUB_TOKEN="$1"
REPOSITORY="$2"
ISSUE_NUMBER="$3"
OPENAI_API_KEY="$4"

# -------------------------------
# Step 1: (Mock) Fetch issue body
# -------------------------------
# In real use: fetch from GitHub API
ISSUE_BODY="Please write a Python script that prints 'Hello, MockGPT!'"

# -------------------------------
# Step 2: Prepare prompt and send to mock GPT
# -------------------------------
PROMPT=$(jq -n --arg body "$ISSUE_BODY" '{
  model: "gpt-3.5-turbo",
  messages: [{"role": "user", "content": $body}],
  max_tokens: 100
}')

RESPONSE=$(curl -s -X POST https://mockgpt.wiremock.io/v1/chat/completions \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -H "Content-Type: application/json" \
  -d "$PROMPT")

echo "MockGPT response received."

# -------------------------------
# Step 3: Simulate code generation
# -------------------------------
mkdir -p autocoder-bot
cat << EOF > autocoder-bot/hello.py
# This is a simulated file generated by MockGPT
print("Hello, MockGPT!")
EOF

echo "Generated file: autocoder-bot/hello.py"
