name: Access Issue Information

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  access_issue_info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Issue and Print Info
        run: |
          if [ -z "${{ github.event.issue.number }}" ]; then
            echo "No open issues found."
          else
            echo "Issue Number: ${{ github.event.issue.number }}"
            echo "Issue Title: ${{ github.event.issue.title }}"
            echo "Issue Body: ${{ github.event.issue.body }}"
            echo "Issue Assignees: ${{ join(github.event.issue.assignees.*.login, ', ') }}"
            echo "Issue Labels: ${{ join(github.event.issue.labels.*.name, ', ') }}"
          fi

          echo "Issue Assignees: ${ISSUE_ASSIGNEES}"
          echo "Issue Labels: ${ISSUE_LABELS}"
