name: DeepSeek AutoCoder

on:
  issues:
    types: [opened, labeled, reopened]

jobs:
  code-generation:
    name: Generate Code with DeepSeek
    if: |
      contains(github.event.issue.labels.*.name, 'autocoder-bot') &&
      (github.event.action == 'opened' || 
       github.event.action == 'labeled' || 
       github.event.action == 'reopened')
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          chmod +x ./scripts/script.sh
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Run DeepSeek AutoCoder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: |
          ./scripts/script.sh \
            "$GITHUB_TOKEN" \
            "$REPOSITORY" \
            "$ISSUE_NUMBER" \
            "$DEEPSEEK_API_KEY"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: |
            autocoder-bot/**
          retention-days: 3

      - name: Verify Artifacts
        run: |
          echo "Generated files structure:"
          find autocoder-bot -type f -print
          [ -d "autocoder-bot" ] || { echo "No files generated!"; exit 1; }
